### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by Xuanyiyiren** [allefeld/pytikz#10]
Hello, I have been looking for such thing for a long time. I can't stand tikz's language any more when I have to do some automatic calculation in latex package tikz. 
But I am new in python and when I try to install your package, something wrong happend:
![9d6a2ae1d4898fc8f7415d70b8c77cc5.png](https://i.miji.bid/2024/02/24/9d6a2ae1d4898fc8f7415d70b8c77cc5.png)

I also tried to install other packages and successed.
![2dfcfa6affa6938f200217089ab2834d.png](https://i.miji.bid/2024/02/24/2dfcfa6affa6938f200217089ab2834d.png)

**Comment by allefeld** [comment]
The problem seems to be that `README.md` is a UTF-8 file and `setup.py` does not explicitly specify that. If the user has a UTF-8 encoding configured it works, on your system with encoding gbk it doesn't.

I tried to fix it in f1d3958753fc062be3282905605a3bf78342b8b1, please try again.

**Comment by Xuanyiyiren** [comment]
This issue has been resolved. Thank you for your help!
![7a10e24ab8f5edb577385c56f0035f67.png](https://i.miji.bid/2024/02/26/7a10e24ab8f5edb577385c56f0035f67.png)

**Comment by allefeld** [comment]
Great!
