### ISSUE TITLE
'Document' object has no attribute 'loadPage'

### ISSUE THREAD

**Issue by AjeyDikshit** [allefeld/pytikz#4]
Every time, I try to display the Picture() instance in Jupyter notebook, it gives this error.

![image](https://user-images.githubusercontent.com/106580444/195007656-8b847ccb-ad34-46a4-9980-6326bdb09d4c.png)

**Comment by allefeld** [comment]
My guess is that this has to do with an API change in one of the packages I use.
I'll look into it.

**Comment by abdullahkhalids** [comment]
Hey! I just encountered this issue. The issue is that pymupdf (that fitz uses) has changed its api. The changes are documented here https://pymupdf.readthedocs.io/en/latest/znames.html

For the error above, you need to change the _get_SVG and _get_PNG functions as follows: 

  ```
  def _get_SVG(self):
        "return SVG data of `Picture`"
        # convert PDF to SVG using PyMuPDF
        doc = fitz.open(self.temp_pdf)
        page = doc.load_page(0)
        svg = page.get_svg_image()
        return svg

    def _get_PNG(self, dpi=None):
        "return PNG data of `Picture`"
        if dpi is None:
            dpi = cfg.display_dpi
        # convert PDF to PNG using PyMuPDF
        zoom = dpi / 72
        doc = fitz.open(self.temp_pdf)
        page = doc.load_page(0)
        pix = page.get_pixmap(matrix=fitz.Matrix(zoom, zoom))
        return pix.tobytes()
```

**Comment by allefeld** [comment]
@abdullahkhalids thanks for looking into this!
Would you like to do a PR? Otherwise I'll copy your code and commit it myself.

**Comment by abdullahkhalids** [comment]
Also, can I say thank you so much for this library. I finally don't want to bang my head against my desk when using tikz.

**Comment by allefeld** [comment]
Great, merged it and appears to work.
And I'm glad someone beside myself finds this useful!
